#include <stdint.h>

typedef uint8_t VlcbTimeWeekDay;
enum VlcbTimeWeekDay {
  VLCB_TIME_WEEK_DAY_SUN = 1,
  VLCB_TIME_WEEK_DAY_MON = 2,
  VLCB_TIME_WEEK_DAY_TUE = 3,
  VLCB_TIME_WEEK_DAY_WED = 4,
  VLCB_TIME_WEEK_DAY_THU = 5,
  VLCB_TIME_WEEK_DAY_FRI = 6,
  VLCB_TIME_WEEK_DAY_SAT = 7,
};

typedef uint8_t VlcbTimeMonth;
enum VlcbTimeMonth {
  VLCB_TIME_MONTH_JAN = 1,
  VLCB_TIME_MONTH_FEB = 2,
  VLCB_TIME_MONTH_MAR = 3,
  VLCB_TIME_MONTH_APR = 4,
  VLCB_TIME_MONTH_MAY = 5,
  VLCB_TIME_MONTH_JUN = 6,
  VLCB_TIME_MONTH_JUL = 7,
  VLCB_TIME_MONTH_AUG = 8,
  VLCB_TIME_MONTH_SEP = 9,
  VLCB_TIME_MONTH_OCT = 10,
  VLCB_TIME_MONTH_NOV = 11,
  VLCB_TIME_MONTH_DEC = 12,
};
